apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mail  # ğŸ‘ˆ åŠ é€™è¡Œï¼


resources:
  - clusterissuer-godaddy.yaml  # â›” ClusterIssuer æ˜¯ cluster-scopeï¼Œä¸èƒ½åŠ  namespaceï¼

secretGenerator:
  - name: godaddy-api-secret
    envs:
      - .env

generatorOptions:
  disableNameSuffixHash: true
